### ISSUE TITLE
100% cpu load

### ISSUE THREAD

**Issue by bercutes** [TON-Pool/miner#11]
windows 10, nvidia 466.77, cuda 11.5, cpu g4600. gpus 1070 and 1066
100% cpu load
miner 0.3.4

**Comment by nosorog777** [comment]
Такая же проблема:  windows 10, nvidia 497.29,   CPU G3900 @ 2.90GHz. gpus 1660s и 3060ti майнер со
100% загрузкой процессора
0.3.4

**Comment by poochh** [comment]
Тоже проблема на windows 10. CPU G4400.
При запуске любых двух видеокарт и более,процессор загружается на 100%
Из-за этого не могу майнить на вашем пуле.
Другие майнеры уже решили эту проблему. Например:
https://github.com/toncoinminer/tonminer/releases
https://github.com/toncoinpool/stratum-miner/releases

**Comment by guntell** [comment]
Тот же Win10. CPU Celeron G4400. На 7 картах 3080 ужас проц колбасит и ядра GPU прыгают с 0 до 100 постоянно

**Comment by tonpool** [comment]
will optimize in next version
