### ISSUE TITLE
No way to change/delete/transfer your wallet address in the @next_ton_pool_bot bot

### ISSUE THREAD

**Issue by am1re** [TON-Pool/miner#16]
At the moment, there is no way to change/delete/transfer your wallet address in the @next_ton_pool_bot bot. To link a new wallet, you will need a new Telegram account.
This is super inconvenient because new version of wallets arrived with subscription support and address of wallet changed and i cant change it in bot to track mining process
Please resolve asap thank you :)

**Comment by tonpool** [comment]
We will consider about this.
