### ISSUE TITLE
6700XT

### ISSUE THREAD

**Issue by Onebet163** [TON-Pool/miner#2]
Does not detect 6700XT
Rig: 4x6700xt

Total devices: 0

Pic:
https://ibb.co/xJMLgWP

**Comment by tonpool** [comment]
We are working on this.

**Comment by viperson888** [comment]
6600xt too

**Comment by AdmiralArtemiy** [comment]
5700/5700xt/6700xt too. HIVE OS.

**Comment by tonpool** [comment]
Try version [0.3.4](https://github.com/TON-Pool/miner/releases/tag/0.3.4), it should work now.

**Comment by Onebet163** [comment]
It works. I would like to see that the bot shows the approximate income per day

**Comment by viperson888** [comment]
Thanks! Works for me!)

сб, 18 дек. 2021 г., 14:50 Ян ***@***.***>:
