### ISSUE TITLE
.

### ISSUE THREAD

**Issue by faredus** [TON-Pool/miner#26]

**Comment by MPCodeWriter21** [comment]
Hi there!

Instructions for TON-Pool.com:

First, you have to register your TONCOIN address in https://t.me/next_ton_pool_bot and after mining 0.22 TON or more you can withdraw your Toncoins.

You can use:

- `/balance` command to see your balance.
- `/withdraw` command to withdraw your funds.

Please note that the pool will take 0.02 TON as a network fee, which means that if you withdraw 0.22 TON you will receive 0.2 TON.
