### ISSUE TITLE
public api to get balance for 3rd party app integration

### ISSUE THREAD

**Issue by KralMurat** [TON-Pool/miner#27]
Hello, 

I have my own application to track my mining revenues, profits, costs etc. And I want to implement my toncoin input to my application. Can you provide a public api to fetch my balance?

https://next.ton-pool.com/wallet/WALLET_ID
https://next.ton-pool.club/wallet/WALLET_ID

I found this, but it returns unnecessary infos, such as : {"ok":true,"registered":true}

for example tonwhales pool has similar api:

https://pool.services.tonwhales.com/wallet/WALLET_ID

and it returns balance too, such as : {"ok":true,"balance":48582400,"registered":true}

Looks like you're using same infrastructure since the responses are almost same, can you please add balance parameter to the api so we can use it to implement 3rd party tracking apps, instead using very unuseful (for developers) telegram bot:)

**Comment by tonpool** [comment]
We will consider about this.

**Comment by EvgeniyKorepov** [comment]
I join the petition. It is very inconvenient for users not to know the current balance.

![image](https://user-images.githubusercontent.com/35364901/155084840-fda33d0c-e9a4-490f-a459-3e3be425cb93.png)
