### ISSUE TITLE
more then 8 gpu

### ISSUE THREAD

**Issue by kerimsagol1** [TON-Pool/miner#3]
I have 13 cards but ony 8 is working.

**Comment by tonpool** [comment]
If the 5 cards are AMD cards, try version [0.3.4](https://github.com/TON-Pool/miner/releases/tag/0.3.4), it should work now.

**Comment by Runningwarrior08** [comment]
I run 12 Nvidia with no issue

**Comment by PimpaDimpa** [comment]
I also do not start more than 8 video cards.
The farm has 12 cards.

NVidia P106-100
Driver N430.64
HiveOS 0.6-146@200714
MB - B250B OEM (5.12 01/17/2018)
CPU - 2 × Intel(R) Celeron(R) CPU G3930 @ 2.90GHz AES

**Comment by NabiKAZ** [comment]
@Runningwarrior08 Would let I know what bit rate it gives you with this number of graphics cards?
