### ISSUE TITLE
fresh ATI cards do not work

### ISSUE THREAD

**Issue by Eujenvanino** [TON-Pool/miner#4]
The whole series 5xxx 5600-5700
The whole series 6xxx 6700-6900
Does not work

**Comment by AdmiralArtemiy** [comment]
+
On hive with 3.3 or any other version of tonminer 5700/5700xt/6700xt don`t work.

**Comment by tonpool** [comment]
Try version [0.3.4](https://github.com/TON-Pool/miner/releases/tag/0.3.4), it should work now.

**Comment by blthlt** [comment]
> Try version [0.3.4](https://github.com/TON-Pool/miner/releases/tag/0.3.4), it should work now.

6600xt's are not working in HIVEOS
